from agents.agent import Agent
from agents.vanilla_agent import VanillaAgent
from agents.replay_agent import ReplayAgent
from agents.priority_replay_agent import PriorityReplayAgent
from agents.priority_dyna_agent import PriorityDynaAgent
from agents.onpolicy_dyna_agent import OnPolicyDynaAgent
from agents.planning2explore_agent import Planning2ExploreAgent
from agents.dyna_agent import DynaAgent
from agents.tabular_agents import *